"""empty message

Revision ID: 08e236f3abd5
Revises: f866c764e16f
Create Date: 2018-05-13 09:51:25.847277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e236f3abd5'
down_revision = 'f866c764e16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=36), nullable=True),
    sa.Column('user_sn', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('main_image', sa.String(length=64), nullable=True),
    sa.Column('describe', sa.String(length=500), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_sn', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=36), nullable=True),
    sa.Column('user_sn', sa.String(length=36), nullable=False),
    sa.Column('seller_sn', sa.String(length=36), nullable=False),
    sa.Column('item_sn', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('main_image', sa.String(length=64), nullable=True),
    sa.Column('people', sa.String(length=36), nullable=True),
    sa.Column('mobile', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=36), nullable=True),
    sa.Column('account', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(length=64), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('item_order')
    op.drop_table('item_image')
    op.drop_table('item')
    # ### end Alembic commands ###
