"""empty message

Revision ID: 7d99bd6dbfb6
Revises: d4cf83126a67
Create Date: 2018-05-12 19:34:30.778364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d99bd6dbfb6'
down_revision = 'd4cf83126a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.alter_column('item', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.add_column('item_order', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('item_order', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('item_order', sa.Column('item_name', sa.String(length=80), nullable=False))
    op.add_column('item_order', sa.Column('item_price', sa.Integer(), nullable=False))
    op.add_column('item_order', sa.Column('main_image', sa.String(length=64), nullable=True))
    op.add_column('item_order', sa.Column('mobile', sa.String(length=36), nullable=True))
    op.add_column('item_order', sa.Column('pay_time', sa.DateTime(), nullable=True))
    op.add_column('item_order', sa.Column('people', sa.String(length=36), nullable=True))
    op.add_column('item_order', sa.Column('seller_sn', sa.String(length=36), nullable=False))
    op.add_column('item_order', sa.Column('user_sn', sa.String(length=36), nullable=False))
    op.drop_column('item_order', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_order', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('item_order', 'user_sn')
    op.drop_column('item_order', 'seller_sn')
    op.drop_column('item_order', 'people')
    op.drop_column('item_order', 'pay_time')
    op.drop_column('item_order', 'mobile')
    op.drop_column('item_order', 'main_image')
    op.drop_column('item_order', 'item_price')
    op.drop_column('item_order', 'item_name')
    op.drop_column('item_order', 'deleted')
    op.drop_column('item_order', 'address')
    op.alter_column('item', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('item', 'deleted')
    # ### end Alembic commands ###
