"""empty message

Revision ID: f866c764e16f
Revises: 7d99bd6dbfb6
Create Date: 2018-05-12 20:43:23.336690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866c764e16f'
down_revision = '7d99bd6dbfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_order', sa.Column('sn', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'item_order', ['sn'])
    op.add_column('user_address', sa.Column('sn', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'user_address', ['sn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='unique')
    op.drop_column('user_address', 'sn')
    op.drop_constraint(None, 'item_order', type_='unique')
    op.drop_column('item_order', 'sn')
    # ### end Alembic commands ###
